# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Publications
    url: publications/
    weight: 12
  - name: Teaching
    url: teaching/
    weight: 13
  # - name: News
  #   url: /#news
  #   weight: 13
  - name: Research
    url: research/
    # this allows a drop down; but it looks ugly and you lose the landing page
    # identifier: research
    weight: 11
  # - name: A Tale of Two Conservations
  #   parent: research
  #   url: research/two-tale/
  #   weight: 10
  # - name: Giving Voice to Historic Property Owners
  #   parent: research
  #   url: research/give-voice/
  #   weight: 10
  # - name: Courses
  #   url: courses/
  #   weight: 40
